### ISSUE TITLE
Add a temporary "We are hiring"-bar

### ISSUE THREAD

**Issue by stovatt** [aesirkth/website#38]
Matias wants a bar at the top of the page that says "We are hiring! Scroll down to apply!"

**Comment by eweilow** [comment]
Get Matias to get an account on GitHub so that we can have a discussion about it during implementation 👍

**Comment by eweilow** [comment]
And tell him that once he does get an account to comment on this issue and I'll add him to the organisation

**Comment by MatiasKidron** [comment]
Here I am!

**Comment by eweilow** [comment]
Forgive my crude sketch, is this general idea what you had in mind?

![image](https://user-images.githubusercontent.com/1054111/36857032-c59e45be-1d77-11e8-94d7-c69d5dc11803.png)

**Comment by MatiasKidron** [comment]
<img width="679" alt="screenshot at mar 01 17-48-55" src="https://user-images.githubusercontent.com/36964231/36857446-da43dfd2-1d78-11e8-8a25-ebef328fc277.png">

Something like this

**Comment by MatiasKidron** [comment]
Maybe we could use the same design as in "remove before flight tags" ?

**Comment by eweilow** [comment]
I'd prefer to make it a more centralized part of the entire website rather than put up a big screaming box 😄

Found this screenshot from last year - I'd be more happy with something like this being emphasised (perhaps in some form directly above _Who we are_?):
![image](https://user-images.githubusercontent.com/1054111/36858306-1591fd60-1d7b-11e8-9d2d-abaa64199c1d.png)

However: Maybe the discussion needs to be had on _why_ we have the website? I think the major points that we've talked about in the past is for people to be recruited and for possible sponsors to learn about us, but maybe those two ideas should become 3 distinct focuses:
- Recruiting students at KTH
- Getting sponsors
- Learning interested people about ÆSIR

This would most likely entail splitting out the main page into something like 2 subpages (one for recruitment, one for sponsors)

**Comment by MatiasKidron** [comment]
Yeah I just thought to have the bar for just 1-2 weeks. I have been promoting the PR person position so I believe that most of the traffic on our page in the next few weeks will be just the people who want to apply so I thought to make it easy for them :) 

Basically all I want is to make it as easy as possible to get information about how you can join/apply.

**Comment by eweilow** [comment]
Okay, I understand! I can add something like that for a week or two, tagging you when there's anything to see 👍 

We should however think about the points I made above for a longer term solution, probably in
https://github.com/aesirkth/website/issues/41

**Comment by eweilow** [comment]
Just curious if you got a notification/alert for this https://github.com/aesirkth/website/pull/46 @MatiasKidron

**Comment by MatiasKidron** [comment]
Have we received any application during last 7 days?

**Comment by eweilow** [comment]
Patrick would be the one to ask, but it doesn't appear so from what I can tell.

**Comment by MatiasKidron** [comment]
Ok!

**Comment by eweilow** [comment]
And it's merged! Hope that someone sees it.
