### ISSUE TITLE
Update text and pictures

### ISSUE THREAD

**Issue by Monras** [aesirkth/website#49]
My suggestions for updates to the website :) Would love some help or guidance on how to make the changes. 

Update: "We are currently working towards a late 2017 launch of Odin, a tiny yet powerful rocket." 
to: "We are currently preparing for the first launch of Odin in late October 2018, follow us on Instagram or Facebook for more frequent updates!"

Add these 2 images (can replace the old "model rocket image" to the Surtr one)
![aesir_ths_website](https://user-images.githubusercontent.com/42514622/44310956-5d1cc080-a3df-11e8-898b-b50a2c0fc0ed.png)
![surtr_launch](https://user-images.githubusercontent.com/42514622/44310958-6a39af80-a3df-11e8-8018-479ce9ec0b18.JPG)

Lastly remove Economy Responsible for Odin (since the project is almost done) and add one for IT/website-responsible instead. Then one for just Surtr (model rockets), one for Odin and lastly one where anyone can pitch new projects perhaps? :) 

Can write more exact text if needed!

**Comment by Monras** [comment]
Oh and update: "We are also in the initial planning phase for a student payload as part of the PERSEUS Project within Europe." 
to: "During the fall of 2017 and spring 2018 some of our members participated in a collaboration with the the French government space agency CNES as a part of their PERSEUS project. The project and experiment we constructed (named Vidar "He from the forrest", one of Odins more strong and mystical sons) to fly on their rocket, was finished on time and the whole team later participated in a seminar in Paris. Unfortunatly the launch, planned to be in Sweden, Kiruna at Esrange was cancelled and postponed till further notice."

Or something like that :)

**Comment by stovatt** [comment]
There is a description how to remove a position in #37. If you want IT/website instead you can just replace the text instead of removing it.

**Comment by stovatt** [comment]
I made a pull request for changing the Odin text. I think the Vidar text should focus more on what the experiment actually was.

Maybe something like: "During the fall of 2017 and spring 2018 some of our members participated in a collaboration with the the French government space agency CNES as a part of their PERSEUS project. The project was to construct an experiment to fly on their rocket.

Our team decided to build a device that would measure the vibrations of the rocket. The project was finished on time and the whole team later participated in a seminar in Paris. Unfortunatly the launch, planned to be in Sweden, Kiruna at Esrange was postponed till further notice due to problems with the rocket."

We should also have a picture of the finished payload.

**Comment by stovatt** [comment]
If I understand correctly you want to have separate application forms for the different projects? I think the way it is now with one Join us form is good.

**Comment by Monras** [comment]
![26962125_176237116471774_1801728524072774476_o](https://user-images.githubusercontent.com/42514622/44311653-66138f00-a3eb-11e8-84da-d10ca49bbce0.jpg)
![28058812_191712661589234_4918677392073487431_n](https://user-images.githubusercontent.com/42514622/44311654-69a71600-a3eb-11e8-8a79-8c495915fa03.jpg)
![20180118_162958](https://user-images.githubusercontent.com/42514622/44311655-6f9cf700-a3eb-11e8-8cf7-8fd3cdeb7aef.jpg)

Yes that is a better text! These are the best Vidar picture (I think). 

Think it would be more clear if there was like a set Odin, Surtr form, one for each project. But an overall join us form covers it all so maybe just add a section to inform that they can join a specific group (Odin and Surtr). That way we can sort out easier who wants to be in Odin (where not all will be accepted) and Surtr (where all is accepted, as long as we have capability for them).

**Comment by stovatt** [comment]
I like the first one. You can change the text at this place.
![screen shot 2018-08-19 at 19 35 16](https://user-images.githubusercontent.com/25963744/44311774-e5a25d80-a3ed-11e8-9213-e0a0c8739ea4.png)

With the amount of applications we have from the website I would say that it it not a problem to sort out who is interested in what and it would be better to just have a "join us!" because that is more friendly and it lets you join the association and not a specific project, which is in my opinion what we want.

**Comment by Monras** [comment]
It does sound more friendly with just one join us option. I suggest then that we remove the other "roles" options for application and have like just a board with what we are especially looking for atm. We need some guidance so that they know what they can do if they join the association. But this is basically the same as it is now, right?

**Comment by wilsoniumite** [comment]
Given that the launch has now passed (and we are now referencing the website quite often) we should update the webpage information very soon, as right now will have some of the highest traffic it will get.

**Comment by eweilow** [comment]
@Wilsontomass I agree. The video that is being worked on should definitely be added to the site 👍
We should also add pictures and such. 

Before we do much alterations, I'd like to merge #56, #57 and #55 
Gonna check up on those with @Monras if I can find him today.

Would you be able to assist with the work on updating the page? You're also invited to the organisation 💯

**Comment by eweilow** [comment]
Continuing this thread in #59 👍
